Update scrapers_runner.yml

diff --git a/.github/workflows/scrapers_runner.yml b/.github/workflows/scrapers_runner.yml
--- a/.github/workflows/scrapers_runner.yml
+++ b/.github/workflows/scrapers_runner.yml
@@ -25,30 +25,45 @@ jobs:
       run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt
+        pip3 install allure-pytest
         sudo apt-get install curl
 
-    - name: All scrapers run
-      env:
-        API_KEY: ${{ secrets.API_KEY }}
-      run: |
-        python3 sites/script_runner.py || true
-        echo "Continuing despite potential failure..."
+    # - name: All scrapers run
+    #   env:
+    #     API_KEY: ${{ secrets.API_KEY }}
+    #   run: |
+    #     python3 sites/script_runner.py || true
+    #     echo "Continuing despite potential failure..."
     
-    - name: Run pytest with HTML reporting
+    - name: Set up Java
+      uses: actions/setup-java@v2
+      with:
+        distribution: 'adopt'
+        java-version: '11'
+
+    - name: Install Allure Command-Line
+      run: |
+        sudo apt-add-repository -y ppa:qameta/allure
+        sudo apt-get update
+        sudo apt-get install allure
+
+    - name: Run pytest with HTML Allure Reporting
       continue-on-error: true
       run: |
-        pytest -m regression -vv --html=api_test_report.html
+        pytest -m regression -vv --alluredir=./allure-results
     
-    - name: Move api_report.html to docs folder
-      run: mv api_test_report.html "docs/api_test_report.html"
+    - name: Compile the allure json files into a single html report
+      run: allure generate --single-file
 
-    - name: Commit and push api_test_report.html
+    - name: Move api_test_report_allure.html to docs folder
+      run: mv -force "allure-report/index.html" "docs/api_test_report_allure.html"
+
+    - name: Commit and push api_test_report_allure.html
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
-        git add "docs/api_test_report.html"
-        git commit -m "Add pytest API HTML report"
+        git add "docs/api_test_report_allure.html"
+        git commit -m "Add pytest API HTML Allure Report"
         git push origin main
-
 
 
