Added job scraping back to workflow

diff --git a/.github/workflows/scrapers_runner.yml b/.github/workflows/scrapers_runner.yml
--- a/.github/workflows/scrapers_runner.yml
+++ b/.github/workflows/scrapers_runner.yml
@@ -27,13 +27,12 @@ jobs:
         pip3 install -r requirements.txt
         sudo apt-get install curl
 
-    # Commented out as per your original workflow
-    # - name: All scrapers run
-    #   env:
-    #     API_KEY: ${{ secrets.API_KEY }}
-    #   run: |
-    #     python3 sites/script_runner.py || true
-    #     echo "Continuing despite potential failure..."
+    - name: All scrapers run
+      env:
+        API_KEY: ${{ secrets.API_KEY }}
+      run: |
+        python3 sites/script_runner.py || true
+        echo "Continuing despite potential failure..."
     
     - name: Run pytest with HTML reporting
       continue-on-error: true
